/*
  Source-linked historical calendar content model.

  dateStart/dateEnd use ISO dates where the historical record supports them.
  For less precise dates, keep the shortest honest value (YYYY or YYYY-MM)
  and describe the precision explicitly.
*/
window.BOTSWANA_SOURCES = Object.freeze({
  embassyHistory: {
    label: "Embassy of the Republic of Botswana — History of Botswana",
    publisher: "Embassy of the Republic of Botswana, Washington, D.C.",
    url: "https://botswanaembassy.org/page/history-of-botswana",
  },
  parliamentHistory: {
    label: "Parliament of Botswana — History of Parliament",
    publisher: "Parliament of Botswana",
    url: "https://www.parliament.gov.bw/index.php?Itemid=163&id=6&option=com_content&view=article",
  },
  independenceHistory: {
    label: "DailyNews — Birth of nation",
    publisher: "Botswana DailyNews / BOPA",
    url: "https://dailynews.gov.bw/news-detail/31255",
  },
  diamondDiscovery: {
    label: "DailyNews — Diamonds cornerstone of economy",
    publisher: "Botswana DailyNews / BOPA",
    url: "https://dailynews.gov.bw/news-detail/35826",
  },
  orapaMine: {
    label: "DailyNews — Orapa mine history",
    publisher: "Botswana DailyNews",
    url: "https://dailynews.gov.bw/news-detail/7405",
  },
  bnrIndex: {
    label: "Botswana Notes & Records publication index",
    publisher: "The Botswana Society",
    url: "https://www.thebotswanasociety.net/botswana-notes-records",
  },
  ipu1969Election: {
    label: "Botswana National Assembly October 1969 Election",
    publisher: "Inter-Parliamentary Union Parline",
    url: "https://data.ipu.org/election-summary/PDF/BOTSWANA_1969_E.PDF",
  },
  ipu1974Election: {
    label: "Botswana National Assembly October 1974 Election",
    publisher: "Inter-Parliamentary Union Parline",
    url: "https://data.ipu.org/election-summary/PDF/BOTSWANA_1974_E.PDF",
  },
  statsBotsCensus: {
    label: "Statistics Botswana — Census History",
    publisher: "Statistics Botswana",
    url: "https://www.statsbots.org.bw/census-history",
  },
  unCensusDates: {
    label: "United Nations — World Population and Housing Census Programme",
    publisher: "United Nations Statistics Division",
    url: "https://unstats.un.org/unsd/demographic-social/census/censusdates",
  },
  developmentPlans: {
    label: "National Planning Commission — National Development Plans",
    publisher: "National Planning Commission, Government of Botswana",
    url: "https://www.npc.gov.bw/national-development-plans",
  },
  dailynewsCategories: {
    label: "Botswana DailyNews — dated article categories",
    publisher: "Botswana DailyNews / BOPA",
    url: "https://dailynews.gov.bw/news-list/srccategory/33/1",
  },
});

const CURATED_BOTSWANA_EVENTS = [
  {
    id: "bechuanaland-protectorate",
    dateStart: "1885",
    dateEnd: null,
    precision: "year",
    title: "Bechuanaland Protectorate established",
    category: "political",
    importance: 5,
    summary: "British protection was established over Bechuanaland after local leaders sought protection from territorial expansion.",
    sources: ["embassyHistory"],
  },
  {
    id: "chiefs-london-delegation",
    dateStart: "1895",
    dateEnd: null,
    precision: "year",
    title: "Chiefs campaign to preserve Bechuanaland’s protection",
    category: "political",
    importance: 4,
    summary: "Three dikgosi travelled to Britain to oppose proposals that would have transferred Bechuanaland to the British South Africa Company.",
    sources: ["embassyHistory"],
  },
  {
    id: "anglo-south-african-war-gaborone",
    dateStart: "1899",
    dateEnd: "1902",
    precision: "range",
    title: "Anglo-South African War affects the Gaborone area",
    category: "political",
    importance: 3,
    summary: "A Botswana Notes & Records study documents events connected to the Anglo-South African War in the Gaborone area between 1899 and 1902.",
    sources: ["bnrIndex"],
    citations: [{ volume: 35, pages: "11–31" }],
  },
  {
    id: "protectorate-union-campaign",
    dateStart: "1908",
    dateEnd: "1910",
    precision: "range",
    title: "Campaign keeps the Protectorate out of the Union",
    category: "political",
    importance: 4,
    summary: "A campaign between 1908 and 1910 worked to keep the Bechuanaland Protectorate outside the Union of South Africa.",
    sources: ["bnrIndex"],
    citations: [{ volume: 27, pages: "85–96" }],
  },
  {
    id: "house-of-chiefs-constitution",
    dateStart: "1961",
    dateEnd: null,
    precision: "year",
    title: "House of Chiefs established under the 1961 Constitution",
    category: "political",
    importance: 3,
    summary: "The 1961 Constitution established a House of Chiefs where traditional leaders could discuss matters affecting their tribes, customs, and privileges.",
    sources: ["parliamentHistory"],
  },
  {
    id: "national-development-planning",
    dateStart: "1965",
    dateEnd: null,
    precision: "year",
    title: "National development planning begins",
    category: "economic",
    importance: 3,
    summary: "Botswana’s first Transitional Plan for Social and Economic Development was prepared as the country moved toward self-government and independence.",
    sources: ["developmentPlans"],
  },
  {
    id: "self-government-elections",
    dateStart: "1965-03",
    dateEnd: null,
    precision: "month",
    title: "First general election and self-government",
    category: "political",
    importance: 4,
    summary: "The March 1965 general election began the transitional period of internal self-government before independence.",
    sources: ["independenceHistory", "embassyHistory"],
  },
  {
    id: "botswana-independence",
    dateStart: "1966-09-30",
    dateEnd: null,
    precision: "day",
    title: "Botswana becomes independent",
    category: "political",
    importance: 5,
    summary: "Bechuanaland became the independent Republic of Botswana, with Sir Seretse Khama as its first president.",
    sources: ["parliamentHistory", "independenceHistory"],
  },
  {
    id: "first-diamond-discovery",
    dateStart: "1967-04-21",
    dateEnd: null,
    precision: "day",
    title: "First diamond discovery at BK01",
    category: "economic",
    importance: 5,
    summary: "Geologists and Batswana explorers identified the BK01 kimberlite near Letlhakane, beginning Botswana’s diamond era.",
    sources: ["diamondDiscovery"],
  },
  {
    id: "mineral-rights-agreement",
    dateStart: "1967",
    dateEnd: null,
    precision: "year",
    title: "Mineral rights placed under national control",
    category: "economic",
    importance: 4,
    summary: "Tribal leaders agreed that mineral rights would be held by the Botswana Government for the benefit of the country’s districts.",
    sources: ["orapaMine"],
  },
  {
    id: "general-election-1969",
    dateStart: "1969-10-18",
    dateEnd: null,
    precision: "day",
    title: "General election of 1969",
    category: "political",
    importance: 4,
    summary: "Botswana held its first general election after independence on 18 October 1969.",
    sources: ["bnrIndex", "ipu1969Election"],
    citations: [{ volume: 3, pages: "32–36" }],
  },
  {
    id: "population-census-1971",
    dateStart: "1971-08",
    dateEnd: null,
    precision: "month",
    title: "Population census of 1971",
    category: "demographic",
    importance: 3,
    summary: "Botswana conducted its first post-independence population census in August 1971.",
    sources: ["bnrIndex", "statsBotsCensus"],
    citations: [{ volume: 4, pages: "31–37" }],
  },
  {
    id: "orapa-mine-opening",
    dateStart: "1971-07-01",
    dateEnd: null,
    precision: "day",
    title: "Orapa mine officially opens",
    category: "economic",
    importance: 5,
    summary: "The Orapa mine was officially opened, turning diamond discoveries into a national mining industry.",
    sources: ["orapaMine"],
  },
  {
    id: "orapa-production",
    dateStart: "1972",
    dateEnd: null,
    precision: "year",
    title: "Orapa production begins",
    category: "economic",
    importance: 4,
    summary: "Commercial production at Orapa began after the mine’s official opening.",
    sources: ["orapaMine"],
  },
  {
    id: "cattle-sample-census-1972",
    dateStart: "1972",
    dateEnd: null,
    precision: "year",
    title: "Cattle sample census",
    category: "economic",
    importance: 2,
    summary: "A national cattle sample census was documented in 1972 as part of Botswana’s agricultural record.",
    sources: ["bnrIndex"],
    citations: [{ volume: 5, pages: "37–40" }],
  },
  {
    id: "general-election-1974",
    dateStart: "1974-10-26",
    dateEnd: null,
    precision: "day",
    title: "General election of 1974",
    category: "political",
    importance: 4,
    summary: "Botswana held its general election on 26 October 1974.",
    sources: ["bnrIndex", "ipu1974Election"],
    citations: [{ volume: 7, pages: "73–77" }],
  },
  {
    id: "kgatleng-drought-1979",
    dateStart: "1979",
    dateEnd: null,
    precision: "year",
    title: "Drought affects crops in Kgatleng",
    category: "environment",
    importance: 3,
    summary: "The 1979 drought affected crops and livelihoods in Kgatleng, as documented in Botswana Notes & Records.",
    sources: ["bnrIndex"],
    citations: [{ volume: 14, pages: "26–29" }],
  },
  {
    id: "seretse-khama-death",
    dateStart: "1980-07-13",
    dateEnd: null,
    precision: "day",
    title: "Sir Seretse Khama dies",
    category: "political",
    importance: 4,
    summary: "Sir Seretse Khama died after serving as Botswana’s first president since independence.",
    sources: ["parliamentHistory", "embassyHistory"],
  },
  {
    id: "seretse-khama-succession",
    dateStart: "1980-07",
    dateEnd: null,
    precision: "month",
    title: "Ketumile Masire succeeds Seretse Khama",
    category: "political",
    importance: 4,
    summary: "Following Seretse Khama’s death, Ketumile Masire became Botswana’s second president.",
    sources: ["embassyHistory"],
  },
  {
    id: "population-census-1981",
    dateStart: "1981-08",
    dateEnd: null,
    precision: "month",
    title: "Population census of 1981",
    category: "demographic",
    importance: 3,
    summary: "The August 1981 population census included migration as an important demographic dimension.",
    sources: ["bnrIndex", "unCensusDates"],
    citations: [{ volume: 17, pages: "89–98" }],
  },
  {
    id: "constitutional-referendum-1987",
    dateStart: "1987",
    dateEnd: null,
    precision: "year",
    title: "Constitutional referendum changes presidential eligibility",
    category: "political",
    importance: 3,
    summary: "A 1987 constitutional amendment changed eligibility for the offices of President and Vice President to Batswana by birth or descent.",
    sources: ["parliamentHistory"],
  },
  {
    id: "jwaneng-mine",
    dateStart: "1982",
    dateEnd: null,
    precision: "year",
    title: "Jwaneng mine begins operations",
    category: "economic",
    importance: 4,
    summary: "Jwaneng began operations and became a major part of Botswana’s diamond economy.",
    sources: ["orapaMine"],
  },
  {
    id: "population-census-1991",
    dateStart: "1991-08-21",
    dateEnd: null,
    precision: "day",
    title: "Population census of 1991",
    category: "demographic",
    importance: 3,
    summary: "Botswana’s 1991 population census was conducted on 21 August 1991.",
    sources: ["bnrIndex", "statsBotsCensus", "unCensusDates"],
    citations: [{ volume: 24, pages: "39–48" }],
  },
  {
    id: "nharo-san-art-exhibit",
    dateStart: "1991-07-02",
    dateEnd: "1991-07-21",
    precision: "range",
    title: "Nharo San art exhibit opens",
    category: "cultural",
    importance: 2,
    summary: "The National Museum and Art Gallery hosted a Nharo San contemporary art exhibit from 2 to 21 July 1991.",
    sources: ["bnrIndex"],
    citations: [{ volume: 23, pages: "286–287" }],
  },
  {
    id: "mogae-presidency",
    dateStart: "1998-04-01",
    dateEnd: null,
    precision: "day",
    title: "Festus Mogae becomes third President",
    category: "political",
    importance: 4,
    summary: "Festus Mogae became Botswana’s third president after Ketumile Masire retired from office.",
    sources: ["parliamentHistory", "embassyHistory"],
  },
  {
    id: "ntlo-ya-dikgosi",
    dateStart: "2007-01",
    dateEnd: null,
    precision: "month",
    title: "Ntlo ya Dikgosi is established",
    category: "political",
    importance: 3,
    summary: "The reformed Ntlo ya Dikgosi was established after constitutional amendments made the traditional advisory institution tribally neutral.",
    sources: ["parliamentHistory"],
  },
  {
    id: "ian-khama-presidency",
    dateStart: "2008",
    dateEnd: null,
    precision: "year",
    title: "Ian Khama becomes fourth President",
    category: "political",
    importance: 3,
    summary: "Ian Khama succeeded Festus Mogae as Botswana’s fourth president.",
    sources: ["embassyHistory"],
  },
];

window.BOTSWANA_EVENTS = Object.freeze([
  ...CURATED_BOTSWANA_EVENTS,
  ...(Array.isArray(window.BOTSWANA_DAILYNEWS_EVENTS) ? window.BOTSWANA_DAILYNEWS_EVENTS : []),
]);
