#!/usr/bin/env python3
"""Build a browser data layer from the reviewed one-lead-per-month queue.

The generated records remain labelled as DailyNews leads. They are useful for
navigation and editorial review, but are not silently promoted to confirmed
historical facts.
"""

from __future__ import annotations

import csv
import json
import re
from datetime import datetime
from pathlib import Path


def clean_text(value: str) -> str:
    replacements = {
        "â€™": "’",
        "â€“": "–",
        "â€”": "—",
        "â€œ": "“",
        "â€\x9d": "”",
        "\\'": "’",
    }
    for old, new in replacements.items():
        value = value.replace(old, new)
    return value.strip()


def importance(score: int) -> int:
    if score >= 16:
        return 3
    if score >= 9:
        return 2
    return 1


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    input_path = root / "data" / "processed" / "dailynews-monthly-review.csv"
    output_path = root / "data" / "processed" / "dailynews-events.js"
    records = []
    for row in csv.DictReader(input_path.open(encoding="utf-8")):
        try:
            date_value = datetime.strptime(row["date"], "%d %b %Y").date().isoformat()
        except ValueError:
            continue
        article_id = re.search(r"(\d+)$", row["url"])
        if not article_id:
            continue
        title = clean_text(row["title"])
        summary = clean_text(row["summary"])
        records.append({
            "id": f"dailynews-{article_id.group(1)}",
            "dateStart": date_value,
            "dateEnd": None,
            "precision": "day",
            "title": f"DailyNews lead: {title}",
            "category": row["category"],
            "importance": importance(int(row.get("score") or 0)),
            "summary": (
                "Newspaper lead retained for editorial review. "
                f"{summary}"
            ),
            "sources": ["dailynewsCategories"],
            "sourceUrl": row["url"],
            "status": "lead",
        })

    output_path.write_text(
        "/* Generated by scripts/build-dailynews-events.py. */\n"
        "window.BOTSWANA_DAILYNEWS_EVENTS = Object.freeze("
        + json.dumps(records, ensure_ascii=False, indent=2)
        + ");\n",
        encoding="utf-8",
    )
    print(f"Built {len(records)} DailyNews timeline leads in {output_path}")


if __name__ == "__main__":
    main()
